import { Audio } from 'expo-av';

export type AudioTier = '2x' | '3x' | '5x' | '7x';

const TIERS: AudioTier[] = ['2x', '3x', '5x', '7x'];

const sounds: Partial<Record<AudioTier, Audio.Sound>> = {};
let initPromise: Promise<void> | null = null;

/**
 * Tries to require an audio asset by tier name. If the file is missing
 * (asset not yet generated by T16, or stripped from a custom build),
 * returns null instead of throwing — initSfx silently no-ops missing tiers.
 */
function tryRequireTier(tier: AudioTier): number | null {
  try {
    switch (tier) {
      case '2x': return require('../../../assets/sounds/merge-2x.m4a');
      case '3x': return require('../../../assets/sounds/merge-3x.m4a');
      case '5x': return require('../../../assets/sounds/merge-5x.m4a');
      case '7x': return require('../../../assets/sounds/merge-7x.m4a');
    }
  } catch {
    return null;
  }
  return null;
}

export async function initSfx(): Promise<void> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    try {
      await Audio.setAudioModeAsync({
        playsInSilentModeIOS: false,
        shouldDuckAndroid: true,
      });
    } catch (e) {
      console.warn('[sfx] failed to set audio mode', e);
    }
    for (const tier of TIERS) {
      const asset = tryRequireTier(tier);
      if (asset === null) {
        console.warn(`[sfx] asset missing for tier ${tier}; skipping`);
        continue;
      }
      try {
        const { sound } = await Audio.Sound.createAsync(asset);
        sounds[tier] = sound;
      } catch (e) {
        console.warn(`[sfx] failed to load ${tier}`, e);
      }
    }
  })();
  return initPromise;
}

export function tierForMultiplier(mult: number): AudioTier | null {
  if (mult < 2) return null;
  if (mult < 3) return '2x';
  if (mult < 5) return '3x';
  if (mult < 7) return '5x';
  return '7x';
}

export async function playMergeSound(multiplier: number): Promise<void> {
  const tier = tierForMultiplier(multiplier);
  if (!tier) return;
  const sound = sounds[tier];
  if (!sound) return;
  try {
    await sound.replayAsync();
  } catch {
    // best-effort
  }
}
